import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import type { EntityEditor } from "../../App";
import type { BackupService } from "../application/backup-service";
import type { SQLiteFinanceRepository } from "../data/sqlite-finance-repository";
import type { Dashboard, InboxEvent, Transaction, TransactionKind } from "../domain/models";
import type { AndroidNotificationProvider } from "../providers/android-notification-provider";
import { Card, EmptyState, SectionTitle, TransactionRow } from "./components";
import { formatMoney, monthLabel, moveMonth } from "./format";
import { colors } from "./theme";

type RefreshProps = { refreshing: boolean; refresh: () => Promise<void> };

export function Home({ data, refreshing, refresh, onEntry, onNew, onCarryover }: RefreshProps & { data: Dashboard; onEntry: (entry: Transaction) => void; onNew: () => void; onCarryover: (enabled: boolean) => void }) {
  const currency = data.profile.currency, locale = data.profile.locale;
  return <ScrollView contentContainerStyle={styles.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.gold} />}>
    <Text style={styles.eyebrow}>VISÃO DO MÊS</Text><Text style={styles.title}>Olá</Text><Text style={styles.subtitle}>Um retrato simples do que entrou, saiu e ficou.</Text>
    <Card style={styles.balanceCard}><Text style={styles.balanceLabel}>SALDO DISPONÍVEL</Text><Text style={[styles.balance, data.summary.remaining < 0 && { color: "#FFB6AE" }]}>{formatMoney(data.summary.remaining, currency, locale)}</Text><Text style={styles.balanceHint}>Contas pendentes não reduzem este valor.</Text></Card>
    <View style={styles.summaryGrid}>
      <Summary label="Receitas" value={data.summary.income} color={colors.green} currency={currency} locale={locale} />
      <Summary label="Despesas" value={data.summary.expenses + data.summary.bills - data.summary.unpaid} color={colors.red} currency={currency} locale={locale} />
      <Summary label="A investir" value={data.summary.estimatedInvested} color={colors.blue} currency={currency} locale={locale} />
      <Summary label="Contas abertas" value={data.summary.unpaid} color={colors.gold} currency={currency} locale={locale} />
    </View>
    <CashFlow data={data} />
    <Card><View style={styles.switchLine}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>Trazer saldo anterior</Text><Text style={styles.rowDetail}>Mantém o saldo de {monthLabel(moveMonth(data.month, -1), locale)} vivo neste mês.</Text></View><Switch value={data.carryoverEnabled} onValueChange={onCarryover} trackColor={{ false: colors.line, true: colors.greenSoft }} thumbColor={data.carryoverEnabled ? colors.green : "#fff"} /></View></Card>
    <View style={styles.sectionGap}><SectionTitle title="Movimentações recentes" subtitle="Toque para revisar ou editar" action={<Pressable onPress={onNew}><Text style={styles.link}>Adicionar</Text></Pressable>} />
      <Card>{data.entries.length ? data.entries.slice(0, 8).map((entry) => <TransactionRow key={entry.id} entry={entry} currency={currency} locale={locale} onPress={() => onEntry(entry)} />) : <EmptyState icon="leaf-outline" title="Um mês em branco" detail="Adicione a primeira receita ou despesa. Tudo ficará somente neste aparelho." />}</Card>
    </View>
  </ScrollView>;
}

function Summary({ label, value, color, currency, locale }: { label: string; value: number; color: string; currency: string; locale: string }) {
  return <Card style={styles.summaryCard}><View style={[styles.summaryDot, { backgroundColor: color }]} /><Text style={styles.summaryLabel}>{label}</Text><Text style={styles.summaryValue}>{formatMoney(value, currency, locale)}</Text></Card>;
}

function CashFlow({ data }: { data: Dashboard }) {
  const max = Math.max(1, ...data.history.flatMap((item) => [item.income, item.expenses + item.bills, item.invested]));
  return <Card style={styles.chartCard}><SectionTitle title="Fluxo dos últimos 6 meses" subtitle="Entradas, saídas e investimentos" /><View style={styles.chart}>{data.history.map((item) => <View key={item.month} style={styles.barGroup}><View style={styles.bars}><View style={[styles.bar, { height: Math.max(2, 72 * Math.max(0, item.income) / max), backgroundColor: colors.green }]} /><View style={[styles.bar, { height: Math.max(2, 72 * (item.expenses + item.bills) / max), backgroundColor: colors.red }]} /><View style={[styles.bar, { height: Math.max(2, 72 * item.invested / max), backgroundColor: colors.blue }]} /></View><Text style={styles.barLabel}>{new Date(`${item.month}-01T12:00:00`).toLocaleDateString(data.profile.locale, { month: "short" }).replace(".", "")}</Text></View>)}</View></Card>;
}

export function Transactions({ data, refreshing, refresh, onEntry }: RefreshProps & { data: Dashboard; onEntry: (entry: Transaction) => void }) {
  const [filter, setFilter] = useState<"all" | TransactionKind>("all");
  const rows = filter === "all" ? data.entries : data.entries.filter((item) => item.kind === filter);
  return <ScrollView contentContainerStyle={styles.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} />}><Text style={styles.title}>Movimentações</Text><Text style={styles.subtitle}>Tudo o que compõe {monthLabel(data.month, data.profile.locale)}.</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{(["all", "income", "expense", "bill", "investment"] as const).map((item) => <Chip key={item} selected={filter === item} onPress={() => setFilter(item)} label={{ all: "Todas", income: "Receitas", expense: "Despesas", bill: "Contas", investment: "Investimentos" }[item]} />)}</ScrollView>
    <Card>{rows.length ? rows.map((entry) => <TransactionRow key={entry.id} entry={entry} currency={data.profile.currency} locale={data.profile.locale} onPress={() => onEntry(entry)} />) : <EmptyState icon="receipt-outline" title="Nada por aqui" detail="Não há movimentações com este filtro no mês." />}</Card>
    {!!data.recurrences.length && <View style={styles.sectionGap}><SectionTitle title="Recorrências ativas" subtitle="A próxima ocorrência nasce localmente quando o mês é aberto" /><Card>{data.recurrences.filter((item) => item.startMonth <= data.month && (!item.endMonth || item.endMonth >= data.month)).map((item) => <View key={item.id} style={styles.listLine}><Ionicons name="repeat" size={18} color={colors.gold} /><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.description}</Text><Text style={styles.rowDetail}>Todo dia {item.day} · {formatMoney(item.amount, data.profile.currency, data.profile.locale)}</Text></View></View>)}</Card></View>}
  </ScrollView>;
}

export function Inbox({ events, data, refreshing, refresh, onAccept, onIgnore }: RefreshProps & { events: InboxEvent[]; data: Dashboard; onAccept: (event: InboxEvent) => void; onIgnore: (event: InboxEvent) => void }) {
  return <ScrollView contentContainerStyle={styles.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} />}><Text style={styles.title}>Inbox financeiro</Text><Text style={styles.subtitle}>Sinais aguardam sua revisão. Nada vira movimentação sem você.</Text>
    {events.length ? events.map((event) => <Card key={event.id} style={styles.inboxCard}><View style={styles.inboxTop}><View style={styles.sourceIcon}><Ionicons name="notifications-outline" size={19} color={colors.gold} /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{event.description ?? "Evento incompleto"}</Text><Text style={styles.rowDetail}>{event.institution ?? event.source} · {new Date(event.occurredAt).toLocaleString(data.profile.locale)}</Text></View>{event.amount != null && <Text style={styles.inboxAmount}>{formatMoney(event.amount, data.profile.currency, data.profile.locale)}</Text>}</View><View style={styles.inboxActions}><Pressable style={styles.secondaryButton} onPress={() => onIgnore(event)}><Text style={styles.secondaryButtonText}>Ignorar</Text></Pressable><Pressable style={styles.primaryButton} onPress={() => onAccept(event)}><Text style={styles.primaryButtonText}>Revisar</Text></Pressable></View></Card>) : <Card><EmptyState icon="checkmark-circle-outline" title="Inbox em dia" detail="Notificações úteis e futuras importações aparecerão aqui para sua confirmação." /></Card>}
  </ScrollView>;
}

export function More({ data, notificationEnabled, refreshing, refresh, openEntity, action, backupService, repository, notificationProvider }: RefreshProps & { data: Dashboard; notificationEnabled: boolean; openEntity: (type: EntityEditor) => void; action: (work: () => Promise<unknown>, success?: string) => Promise<void>; backupService: BackupService; repository: SQLiteFinanceRepository; notificationProvider: AndroidNotificationProvider }) {
  const [passphrase, setPassphrase] = useState("");
  const [currency, setCurrency] = useState(data.profile.currency);
  return <ScrollView contentContainerStyle={styles.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} />}><Text style={styles.title}>Organizar e proteger</Text><Text style={styles.subtitle}>Contas, categorias, automação e backups sob seu controle.</Text>
    <SectionTitle title="Contas e cartões" /><Card>
      {data.accounts.map((item) => <View key={item.id} style={styles.listLine}><View style={[styles.colorDot, { backgroundColor: item.color }]} /><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.name}</Text><Text style={styles.rowDetail}>{item.institution ?? "Conta local"}</Text></View></View>)}
      {data.cards.map((item) => <View key={item.id} style={styles.listLine}><Ionicons name="card-outline" size={20} color={item.color} /><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.name}</Text><Text style={styles.rowDetail}>{item.lastFour ? `Final ${item.lastFour}` : "Cartão"}{item.dueDay ? ` · vence dia ${item.dueDay}` : ""}</Text></View></View>)}
      {!data.accounts.length && !data.cards.length && <Text style={styles.emptyInline}>Ainda não há contas ou cartões. O histórico antigo continuará válido como “não atribuído”.</Text>}
      <View style={styles.twoButtons}><Pressable style={styles.secondaryButton} onPress={() => openEntity("account")}><Text style={styles.secondaryButtonText}>+ Conta</Text></Pressable><Pressable style={styles.secondaryButton} onPress={() => openEntity("card")}><Text style={styles.secondaryButtonText}>+ Cartão</Text></Pressable></View>
    </Card>
    <View style={styles.sectionGap}><SectionTitle title="Categorias e etiquetas" subtitle={`${data.tags.length} itens organizados por tipo de movimentação`} /><Card><View style={styles.tagCloud}>{data.tags.slice(0, 16).map((tag) => <View key={tag.id} style={[styles.tag, { borderColor: tag.color }]}><View style={[styles.colorDot, { backgroundColor: tag.color }]} /><Text style={styles.tagText}>{tag.name}</Text></View>)}</View><Pressable style={styles.secondaryButton} onPress={() => openEntity("tag")}><Text style={styles.secondaryButtonText}>+ Categoria ou etiqueta</Text></Pressable></Card></View>
    <View style={styles.sectionGap}><SectionTitle title="Notificações Android" subtitle="Fonte opcional; o app funciona sem ela" /><Card><View style={styles.switchLine}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{notificationEnabled ? "Acesso concedido" : "Acesso não concedido"}</Text><Text style={styles.rowDetail}>Somente notificações financeiras reconhecidas do Inter são convertidas em candidatos. O texto bruto não é salvo.</Text></View><Ionicons name={notificationEnabled ? "shield-checkmark" : "shield-outline"} size={27} color={notificationEnabled ? colors.green : colors.muted} /></View><Pressable style={styles.secondaryButton} onPress={() => void notificationProvider.openSettings()}><Text style={styles.secondaryButtonText}>Abrir acesso às notificações</Text></Pressable></Card></View>
    <View style={styles.sectionGap}><SectionTitle title="Backup criptografado" subtitle="Você escolhe a pasta, inclusive um provedor do seletor Android" /><Card><TextInput value={passphrase} onChangeText={setPassphrase} placeholder="Senha do backup (mín. 10 caracteres)" placeholderTextColor={colors.muted} secureTextEntry style={styles.input} /><View style={styles.twoButtons}><Pressable style={styles.primaryButton} onPress={() => void action(() => backupService.create(passphrase), "Backup criado no local escolhido.")}><Text style={styles.primaryButtonText}>Criar backup</Text></Pressable><Pressable style={styles.secondaryButton} onPress={() => Alert.alert("Restaurar backup?", "O conteúdo validado substituirá os dados atuais. Uma cópia privada de recuperação será criada antes.", [{ text: "Cancelar", style: "cancel" }, { text: "Continuar", style: "destructive", onPress: () => void action(() => backupService.restore(passphrase), "Backup restaurado e verificado.") }])}><Text style={styles.secondaryButtonText}>Restaurar</Text></Pressable></View><Pressable style={styles.textButton} onPress={() => Alert.alert("Importar histórico web?", "Use somente o JSON criado pela ferramenta de migração deste projeto. A importação é validada e transacional.", [{ text: "Cancelar", style: "cancel" }, { text: "Escolher arquivo", onPress: () => void action(() => backupService.importLegacySnapshot(), "Histórico importado para o SQLite.") }])}><Text style={styles.link}>Importar histórico antigo (.json)</Text></Pressable></Card></View>
    <View style={styles.sectionGap}><SectionTitle title="Preferências" /><Card><Text style={styles.fieldLabel}>Moeda</Text><View style={styles.chips}>{(["BRL", "USD", "EUR"] as const).map((item) => <Chip key={item} label={item} selected={currency === item} onPress={() => setCurrency(item)} />)}</View><Pressable style={styles.primaryButton} onPress={() => void action(() => repository.saveProfile({ ...data.profile, currency }), "Preferências salvas.")}><Text style={styles.primaryButtonText}>Salvar preferências</Text></Pressable></Card></View>
    <Card style={styles.privacyCard}><Ionicons name="lock-closed-outline" size={22} color={colors.green} /><View style={{ flex: 1 }}><Text style={styles.rowTitle}>Privado por arquitetura</Text><Text style={styles.rowDetail}>Sem analytics, crash reporting remoto, contas bancárias, agregadores ou servidor. SQLite é a fonte de verdade.</Text></View></Card>
  </ScrollView>;
}

export function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) {
  return <Pressable onPress={onPress} style={[styles.chip, selected && styles.chipSelected]}><Text style={[styles.chipText, selected && styles.chipTextSelected]}>{label}</Text></Pressable>;
}

export const commonStyles = StyleSheet.create({
  primaryButton: { minHeight: 43, borderRadius: 11, paddingHorizontal: 17, paddingVertical: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.green }, primaryButtonText: { color: "#fff", fontSize: 12, fontWeight: "800" }, secondaryButton: { minHeight: 41, borderRadius: 11, paddingHorizontal: 16, paddingVertical: 11, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, secondaryButtonText: { color: colors.ink, fontSize: 11, fontWeight: "700" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 16 }, chip: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 }, chipSelected: { backgroundColor: colors.greenSoft, borderColor: colors.green }, chipText: { color: colors.muted, fontSize: 11, fontWeight: "600" }, chipTextSelected: { color: colors.green }, fieldLabel: { color: colors.ink, fontSize: 11, fontWeight: "700", marginBottom: 7 }, input: { minHeight: 45, borderRadius: 11, borderWidth: 1, borderColor: colors.line, backgroundColor: "#fff", paddingHorizontal: 13, color: colors.ink, fontSize: 14 }, switchLine: { flexDirection: "row", alignItems: "center", gap: 12 }, rowTitle: { color: colors.ink, fontSize: 13, fontWeight: "700" }, rowDetail: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, link: { color: colors.green, fontSize: 12, fontWeight: "800" }, textButton: { alignItems: "center", padding: 13, marginTop: 4 }, twoButtons: { flexDirection: "row", gap: 9, marginTop: 15 },
});

const styles = StyleSheet.create({
  ...commonStyles,
  scroll: { padding: 20, paddingBottom: 120 }, eyebrow: { color: colors.gold, fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, title: { color: colors.ink, fontSize: 27, lineHeight: 33, fontWeight: "800", marginTop: 6 }, subtitle: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 20 },
  balanceCard: { backgroundColor: colors.ink, borderColor: colors.ink, marginBottom: 12 }, balanceLabel: { color: "#CCD7C6", fontSize: 10, fontWeight: "700", letterSpacing: 1.1 }, balance: { color: "#fff", fontSize: 31, fontWeight: "800", marginTop: 10 }, balanceHint: { color: "#AEBBA8", fontSize: 10, marginTop: 7 },
  summaryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 12 }, summaryCard: { width: "48.5%", minHeight: 105, padding: 15 }, summaryDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 13 }, summaryLabel: { color: colors.muted, fontSize: 10, fontWeight: "700" }, summaryValue: { color: colors.ink, fontSize: 16, fontWeight: "800", marginTop: 7 },
  chartCard: { marginBottom: 12 }, chart: { height: 105, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-around", paddingTop: 8 }, barGroup: { alignItems: "center", flex: 1 }, bars: { height: 75, flexDirection: "row", alignItems: "flex-end", gap: 2 }, bar: { width: 6, borderTopLeftRadius: 3, borderTopRightRadius: 3 }, barLabel: { color: colors.muted, fontSize: 9, marginTop: 7 }, sectionGap: { marginTop: 25 },
  listLine: { flexDirection: "row", alignItems: "center", gap: 11, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, inboxCard: { marginBottom: 10 }, inboxTop: { flexDirection: "row", alignItems: "center", gap: 10 }, sourceIcon: { width: 36, height: 36, backgroundColor: colors.goldSoft, borderRadius: 11, justifyContent: "center", alignItems: "center" }, inboxAmount: { color: colors.ink, fontSize: 14, fontWeight: "800" }, inboxActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 16 },
  tagCloud: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 15 }, tag: { flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 7 }, tagText: { color: colors.ink, fontSize: 10, fontWeight: "600" }, colorDot: { width: 9, height: 9, borderRadius: 5 }, emptyInline: { color: colors.muted, fontSize: 11, lineHeight: 17 }, privacyCard: { flexDirection: "row", gap: 13, alignItems: "flex-start", backgroundColor: colors.greenSoft },
});
